import { CSSProperties } from 'react';
export declare const top: CSSProperties;
export declare const logo: CSSProperties;
export declare const menu: CSSProperties;
export declare const header: CSSProperties;
export declare const headerInverted: CSSProperties;
export declare const headerDepth: CSSProperties;
export declare const menuItemIcon: CSSProperties;
export declare const menuRight: CSSProperties;
export declare const menuLeft: CSSProperties;
export declare const menuItemCurrent: CSSProperties;
export declare const menuItemCurrentInverted: CSSProperties;
export declare const drawer: CSSProperties;
export declare const menuDrawerItem: CSSProperties;
export declare const menuDrawerItemCurrent: CSSProperties;
export declare const menuItem: CSSProperties;
export declare const menuItemInverted: CSSProperties;
